### ISSUE TITLE
Can't find Python executable

### ISSUE THREAD

**Issue by Synj24** [isdampe/music-for-programming#13]
When installing with `npm install -g music-for-programming` i get this error:

```
C:\Users\mgregory\AppData\Roaming\npm\mfp -> C:\Users\mgregory\AppData\Roaming\npm\node_modules\music-for-programming\mfp.js

> lame@1.2.4 install C:\Users\mgregory\AppData\Roaming\npm\node_modules\music-for-programming\node_modules\lame
> node-gyp rebuild


C:\Users\mgregory\AppData\Roaming\npm\node_modules\music-for-programming\node_modules\lame>if not defined npm_config_node_gyp (node "C:\Users\mgregory\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\Users\mgregory\AppData\Local\Programs\Python\Python36-32\", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\mgregory\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\mgregory\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Users\mgregory\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\mgregory\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\mgregory\AppData\Roaming\npm\node_modules\music-for-programming\node_modules\lame
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lame@1.2.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the lame@1.2.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

I have tried setting the PYTHON env variable. and added it to the PATH variable.

Is this an issue with lame or gyp?

## system info
OS windows 7
node -v v8.9.3
npm -v v5.6.0 (also tried with 5.5.1)

Thanks :bowing_man:

**Comment by eorroe** [comment]
Same and on latest Node version and NPM version

**Comment by isdampe** [comment]
I have tested on Windows 10 and had success after updating Python path variables and restarting computer. See here:

https://stackoverflow.com/questions/15126050/running-python-on-windows-for-node-js-dependencies

**Comment by isdampe** [comment]
Closing from inactivity
