### ISSUE TITLE
I got an error while install.

### ISSUE THREAD

**Issue by ljcucc** [isdampe/music-for-programming#16]
I got an error while install this package on termux which is an Android Terminal.

*Need help*

```
gyp ERR! configure error
gyp ERR! stack Error: Command failed: /data/data/com.termux/files/usr/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:297:12)
gyp ERR! stack     at ChildProcess.emit (events.js:197:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:984:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:401:11)
gyp ERR! stack     at Socket.emit (events.js:197:13)
gyp ERR! stack     at Pipe._handle.close (net.js:611:12)
gyp ERR! System Linux 3.18.22
gyp ERR! command "/data/data/com.termux/files/usr/bin/node" "/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /data/data/com.termux/files/home/Desktop/node_modules/lame
gyp ERR! node -v v11.10.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN playground@1.0.0 No description
npm WARN playground@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lame@1.2.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the lame@1.2.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /data/data/com.termux/files/home/.npm/_logs/2019-03-06T00_52_48_330Z-debug.log
```

**Comment by netyaroze** [comment]
> gyp ERR! stack SyntaxError: invalid syntax

Looks like you're running in the wrong version of python.

**Comment by isdampe** [comment]
Try `pkg install python2`
