### ISSUE TITLE
unable to run

### ISSUE THREAD

**Issue by lrdegeest** [isdampe/music-for-programming#7]
Just tried downloading per the instructions, but when I type `mfp` I get the following error:

`/usr/local/lib/node_modules/music-for-programming/mfp.js:310
		api.fetchTracks((err,tracks) => {
		                             ^^
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3`

**Comment by ixcviw7bw** [comment]
What node.js version are you using? You need at least v4 as this project uses arrow functions.

**Comment by isdampe** [comment]
What version of Node.js are you running? Looks like it's an older version that does not support arrow shorthand functions. Is upgrading Node.js to a newer version possible? (Check with node -v)

See https://strongloop.com/strongblog/an-introduction-to-javascript-es6-arrow-functions/
